### ISSUE TITLE
CMS Colour Profiles

### ISSUE THREAD

**Issue by louisevanderlith** [louisevanderlith/theme#3]
Ensure that these classes are used to add colour or shadows to elements

```css
.bgcolourPrimary {
	background-color: rgb(183, 189, 193);
}

.bgcolourSecondary {
	background-color: rgb(56, 187, 157);
}

.bgcolourTertiary {
	background-color: rgb(0, 0, 0);
}

.bgcolourShadows {
	background-color: rgb(25, 145, 173);
}

.bgcolourAccent {
	background-color: rgb(47, 47, 47);
}

.bgcolourBackground {
	background-color: rgb(245, 249, 233);
}

.borderPrimary {
	border-bottom: 2px solid rgb(183, 189, 193);
}

.borderSecondary {
	border-bottom: 2px solid rgb(56, 187, 157);
}

.borderTertiary {
	border-bottom: 2px solid rgb(0, 0, 0);
}

.borderShadows {
	border-bottom: 2px solid rgb(25, 145, 173);
}

.borderAccent {
	border-bottom: 2px solid rgb(47, 47, 47);
}

.borderBackground {
	border-bottom: 2px solid rgb(245, 249, 233);
}

.boxPrimary {
	box-shadow: 0 2px 25px 0 rgba(183, 189, 193, 0.1);
}

.boxSecondary {
	box-shadow: 0 2px 25px 0 rgba(56, 187, 157, 0.1);
}

.boxTertiary {
	box-shadow: 0 2px 25px 0 rgba(0, 0, 0, 0.1);
}

.boxShadows {
	box-shadow: 0 2px 25px 0 rgba(25, 145, 173, 0.1);
}

.boxAccent {
	box-shadow: 0 2px 25px 0 rgba(47, 47, 47, 0.1);
}

.boxBackground {
	box-shadow: 0 2px 25px 0 rgba(245, 249, 233, 0.1);
}

.colourPrimary {
	color: rgb(183, 189, 193);
}

.colourSecondary {
	color: rgb(56, 187, 157);
}

.colourTertiary {
	color: rgb(0, 0, 0);
}

.colourShadows {
	color: rgb(25, 145, 173);
}

.colourAccent {
	color: rgb(47, 47, 47);
}

.colourBackground {
	color: rgb(245, 249, 233);
}

.backgroundPrimary {
	background: rgb(183, 189, 193);
}

.backgroundSecondary {
	background: rgb(56, 187, 157);
}

.backgroundTertiary {
	background: rgb(0, 0, 0);
}

.backgroundShadows {
	background: rgb(25, 145, 173);
}

.backgroundAccent {
	background: rgb(47, 47, 47);
}

.backgroundBackground {
	background: rgb(245, 249, 233);
}
```
